# Main ETL Framework Configuration
# Global configurations and pipeline orchestration

# List of all database connection configurations
databaseConnections:
  - connectionName: "local_pg_main"
    type: "PostgreSQL"
    dbUrl: "jdbc:postgresql://localhost:5432/postgres"
    dbUser: "postgres"
    dbPass: "postgres"
    maxPool: 10
    idleTimeout: 30000
    connTimeout: 5000
    maxLifetime: 1800000
  - connectionName: "office_vpn_pg_ucc"
    type: "PostgreSQL"
    dbUrl: "jdbc:postgresql://192.168.1.22:5444/UCC_Uganda"
    dbUser: "postgres"
    dbPass: "postgres"
    maxPool: 50
  # ... other database connections ...
  - connectionName: "prod_data_warehouse"
    type: "PostgreSQL"
    dbUrl: "jdbc:postgresql://dw.example.com:5432/analytics_db"
    dbUser: "etl_user"
    dbPass: "SecurePassword123!"
    maxPool: 20

# List of all ETL pipelines defined in this framework
etlPipelines:
  # Pipeline 1: AIR Data Processing
  - pipelineName: "AIR_CDR_Processing"
    description: "Processes AIR Call Detail Records."
    pipelineVersion: "1.5"
    active: true # Initial active state for the pipeline
    logFile: "logs/air_cdr_pipeline.log"
    statusDir: "status/air_cdr"
    fileInfoTable: "pipeline_air_process_info"
    routeInfoTable: "pipeline_air_route_info"

    # Path to the detailed configuration file for this pipeline
    pipelineSpecificConfigFile: "sources/air/air.yaml"

    # Core source configurations needed for discovery and initial setup
    sources:
      - sourceId: "STUDENT"
        active: true # Controls if this source within the pipeline is processed
        sourceDir: "data/air/source"
        dirFilter: "glob:*"
        startDir: "20250111"
        endDir: "20250115"
        dataFileType: "CSV"
        fileFilter: "glob:*.csv"
        fileBackup: true
        deleteAfterLoad: false # From source dir before staging DB load
        backupDir: "data/air/backup"
        errBackup: true
        errDir: "data/air/error"
        outDir: "data/air/output_temp" # For intermediate files if any
        useSubDirAsPartition: true
        headerLines: 0
        # Initial values, can be changed by performanceTuning
        numThreads: 1
        batchSize: 5
        # Staging database details
        loadFiles: true # Load raw files to a staging table
        databaseConnectionRef: "local_pg_main"
        tableName: "student_staging" # Staging table name
        keepFileHeader: true
        deleteFilesOnLoadAfterDb: true # From source dir after successful staging DB load
        # (Moved to pipeline-specific file: sourceMetadata, sourceFields, validationRules)

    # Configuration for dynamic performance tuning (remains in main config)
    autoTuning:
      enabled: true
      observationFrequencySeconds: 60
      cooldownPeriodSeconds: 300
      adjustableParameters:
        numThreads: { min: 1, max: 8, incrementStep: 1, decrementStep: 1 }
        batchSize: { min: 10, max: 200, incrementFactor: 1.2, decrementFactor: 0.8 }
      tuningRules:
        - ruleName: "CriticalCPUHigh"
          metric: "systemCpuLoadPercent"
          condition: "greaterThan"
          threshold: 90
          consecutiveBreachesToTrigger: 2
          action: { type: "deactivatePipelineTemporarily", durationMinutes: 15, interimAction: { type: "reduceLoadDrastically", params: { targetNumThreads: "min", targetBatchSizeFactor: 0.5 } } }
        # ... other tuning rules ...

  # Pipeline 2: MFS Transaction Processing
  - pipelineName: "MoMo"
    description: "Processes Mobile Money (MoMo) transaction logs."
    pipelineVersion: "1.0"
    active: false
    logFile: "logs/momo.log"
    statusDir: "status/mfs"
    # ... other high-level MFS pipeline settings ...

    pipelineSpecificConfigFile: "sources/momo/momo.yaml"

    sources:
    - sourceId: "MoMo"
      active: true # Controls if this source within the pipeline is processed
      sourceDir: "data/momo/source"
      dirFilter: "glob:*"
      startDir: "20191130"
      endDir: "20250301"
      dataFileType: "CSV"
      fileFilter: "regex:momo_cdr_\\d+_\\d{8}\\.csv(\\.gz)?"
      fileBackup: true
      deleteAfterLoad: false # From source dir before staging DB load
      backupDir: "data/momo/backup"
      errBackup: true
      errDir: "data/momo/error"
      outDir: "data/momo/output_temp" # For intermediate files if any
      useSubDirAsPartition: true
      headerLines: 0
      # Initial values, can be changed by performanceTuning
      numThreads: 1
      batchSize: 4
      # Staging database details
      loadFiles: true # Load raw files to a staging table
      databaseConnectionRef: "local_pg_main"
      tableName: "momo_trans_raw_staging" # Staging table name
      keepFileHeader: true
      deleteFilesOnLoadAfterDb: true # From source dir after successful staging DB load
      # (Moved to pipeline-specific file: sourceMetadata, sourceFields, validationRules)
      # performanceTuning: ... (can be defined for MFS as well)

#  # Pipeline 3: Gamma Source Data Processing
#  - pipelineName: "Gamma_Source_Processing"
#    description: "Processes Gamma Source data."
#    pipelineVersion: "1.0"
#    active: true
#    logFile: "logs/gamma_source_pipeline.log"
#    statusDir: "status/gamma_source"
#    fileInfoTable: "pipeline_gamma_process_info"
#    routeInfoTable: "pipeline_gamma_route_info"
#
#    # Path to the detailed configuration file for this pipeline
#    pipelineSpecificConfigFile: "sources/gamma_source/gamma_source.yaml"
#
#    # Core source configurations
#    sources:
#      - sourceId: "Gamma_Source_Main" # Must match sourceId in gamma_source.yaml
#        active: true
#        sourceDir: "data/gamma_source/source"
#        dirFilter: "glob:*" # Process all subdirectories
#        startDir: "0"       # Placeholder, adjust if needed
#        endDir: "z"         # Placeholder, adjust if needed
#        dataFileType: "CSV"
#        fileFilter: "glob:*.csv" # Process all CSV files
#        fileBackup: true
#        deleteAfterLoad: false
#        backupDir: "data/gamma_source/backup"
#        errBackup: true
#        errDir: "data/gamma_source/error"
#        outDir: "data/gamma_source/output_temp"
#        useSubDirAsPartition: true # Assuming subdirectories might be used for partitioning
#        headerLines: 1 # Assuming CSV files have a header row
#        # Initial performance values
#        numThreads: 2
#        batchSize: 20
#        # Staging database details
#        loadFiles: true
#        databaseConnectionRef: "local_pg_main" # Defined in databaseConnections
#        tableName: "gamma_trans_raw_staging"
#        keepFileHeader: true
#        deleteFilesOnLoadAfterDb: true
#    # autoTuning can be added here if needed, similar to AIR_CDR_Processing
#    autoTuning:
#      enabled: false # Disabled for now, can be configured later
